### ISSUE TITLE
1.20.1 Bettas and Aquatics crash

### ISSUE THREAD

**Issue by bri3ooh** [ffxvfan/bettas-1.18.2#12]
I downloaded Bettas and Aquatics for 1.20.1 
![image](https://github.com/ffxvfan/bettas-1.18.2/assets/167138524/5cb55f7a-0076-4850-9de3-9bcb7f8f01cf)
I recieved an error message after a few minutes of loading and a crash. I have both Geckolib and Terrablender. 
"The game crashed whilst initializing game
Error: java.lang.IncompatibleClassChangeError: class net.coderbot.iris.gui.option.ShadowDistanceOption cannot inherit from final class net.minecraft.client.OptionInstance"

**Comment by DragN0007** [comment]
I believe this is a compatibility issue with Iris. You could try running it without Iris and seeing if that's the issue! 

If it is, you could try Optifine (which is officially tested with Bettas & Aquatics) or possibly this mod (Geckolib Iris Compat):
https://www.curseforge.com/minecraft/mc-mods/geckoanimfix
