### ISSUE TITLE
Deep Blue Drowning

### ISSUE THREAD

**Issue by RileyCasper** [ffxvfan/bettas-1.18.2#13]
A few of the deep blue whales/sharks drown xD
![image](https://github.com/user-attachments/assets/945f3082-4a0a-4b33-aadc-4cd4d9af2ffe)
![image](https://github.com/user-attachments/assets/ff08ee1c-027e-4c8d-b852-6b7e753379e6)

It's not their enclosure xD That's big enough for sure.
![2024-07-26_12 27 19](https://github.com/user-attachments/assets/2034c4a7-f2f8-44ff-9f0f-388d845ab5c3)

So deeper investigation, Dolphin ai seems to be the culprit. They just float down to the bottom and don't bother to surface for air xD, ultimately drowning themselves.

**Comment by DragN0007** [comment]
OHHH dear

I'll get that fixed for next update LOL. I'll also be including a fix for that one bug where they randomly start levitating above the surface and then they shoot back down under it.. 

My "travel" code is immaculate

**Comment by DragN0007** [comment]
Fixed for 1.1 :) 
If the issue persists after updating, when the update releases, let me know!
